[package]
name = "phoenix"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.1", features = ["full"] }
sonic-rs = "0.4.1"
axum-serde = "0.8.1"
axum = { version = "0.8.3" }
jsonwebtoken = { version = "9.3.1" }
